// Copies contract ABIs + every deployment record into src/lib/generated so the
// frontend can import them as typed constants. Run after `forge build` / a deploy.
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "src/lib/generated");
mkdirSync(out, { recursive: true });

// Production contracts only. The frontend must never be built against a mock ABI:
// if it compiles against MockOracle it will happily call `setPrice` in a UI that
// has no such power on a real chain. IERC20Metadata covers the ERC-20 escrow token
// on chains where the contract is deployed in token mode (Robinhood Chain).
const contracts = ["PyrisPact", "IERC20Metadata"];
let abis = "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n";
for (const name of contracts) {
  const p = resolve(root, `contracts/out/${name}.sol/${name}.json`);
  if (!existsSync(p)) {
    console.error(`missing ${p} — run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(p, "utf8"));
  abis += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n`;
}
writeFileSync(resolve(out, "abis.ts"), abis);

// Every contracts/deployments/<chainId>.json (and local.json = 31337) becomes one entry,
// keyed by chain id. The app is dual chain, so all records ship together; which ones are
// offered is decided at runtime by src/lib/chains.ts.
const depDir = resolve(root, "contracts/deployments");
const map = {};
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir).filter((f) => f.endsWith(".json"))) {
    const dep = JSON.parse(readFileSync(resolve(depDir, f), "utf8"));
    if (typeof dep?.chainId !== "number" || !dep.pyrisPact) continue;
    map[String(dep.chainId)] = dep;
  }
}
const ordered = Object.fromEntries(Object.keys(map).sort((a, b) => Number(a) - Number(b)).map((k) => [k, map[k]]));
writeFileSync(
  resolve(out, "deployments.ts"),
  "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n" +
    `export const deployments = ${JSON.stringify(ordered, null, 2)} as const;\n`,
);
// Kept for older imports: the Arc record (or the first one).
const primary = ordered["5042"] ?? Object.values(ordered)[0] ?? null;
writeFileSync(
  resolve(out, "deployment.ts"),
  "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit. Prefer ./deployments.\n" +
    `export const deployment = ${JSON.stringify(primary, null, 2)} as const;\n`,
);
console.log(`synced ${contracts.length} ABIs; deployments: ${Object.keys(ordered).join(", ") || "none"}`);
