// Copies contract ABIs + the local deployment into src/lib/generated so the
// frontend can import them as typed constants. Run after `forge build` / deploy.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = resolve(root, "src/lib/generated");
mkdirSync(out, { recursive: true });

const contracts = ["PillarCore", "MockERC20", "MockOracle", "MockYieldSource"];
let abis = "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n";
for (const name of contracts) {
  const p = resolve(root, `contracts/out/${name}.sol/${name}.json`);
  if (!existsSync(p)) {
    console.error(`missing ${p} — run \`forge build\` in contracts/ first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(p, "utf8"));
  abis += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n`;
}
writeFileSync(resolve(out, "abis.ts"), abis);

const depPath = resolve(root, "contracts/deployments/local.json");
const dep = existsSync(depPath) ? JSON.parse(readFileSync(depPath, "utf8")) : null;
writeFileSync(
  resolve(out, "deployment.ts"),
  "// AUTO-GENERATED by scripts/sync-abi.mjs — do not edit.\n" +
    `export const deployment = ${JSON.stringify(dep, null, 2)} as const;\n`,
);
console.log(`synced ${contracts.length} ABIs; deployment: ${dep ? dep.pillarCore : "none"}`);
